export const ErrorCode = {
    DEVICE_CONFIG_INVALID: 'DEVICE_CONFIG_INVALID',
    TAG_TYPE_NOT_SUPPORTED: 'TAG_TYPE_NOT_SUPPORTED',
    NODE_ID_DUPLICATE: 'NODE_ID_DUPLICATE',
    CONFIG_FILE_NOT_FOUND: 'CONFIG_FILE_NOT_FOUND',
    DEVICE_REGISTRATION_FAILED: 'DEVICE_REGISTRATION_FAILED',
    SERVER_SHUTDOWN_FAILED: 'SERVER_SHUTDOWN_FAILED',
    SERVER_NOT_RUNNING: 'SERVER_NOT_RUNNING',
    SERVER_UNHEALTHY: 'SERVER_UNHEALTHY',
    DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
    TAG_NOT_FOUND: 'TAG_NOT_FOUND',
    TAG_BROWSE_NAME_AMBIGUOUS: 'TAG_BROWSE_NAME_AMBIGUOUS',
    TAG_SELECTOR_INVALID: 'TAG_SELECTOR_INVALID',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
